### ISSUE TITLE
Exporting liked songs

### ISSUE THREAD

**Issue by pitastrudl** [pavelkomarov/exportify#14]
Hi, I didnt find in the output a csv with my liked songs, is this supported? Is there any limitation in the API for this?

**Comment by pavelkomarov** [comment]
Last I knew, spotify treats your liked songs differently. They're not a playlist. Feel free to dig around the [web API](https://developer.spotify.com/documentation/web-api/) for an elegant way to query for such songs and to make them a line in the table. Better yet, code it and open a pull request. I believe I removed this from the original code because the capability was broken for any reasonably large number of liked songs, and it really felt like an inelegant addendum in the code, and I didn't like having to treat liked songs differently.

If you are desperate to export liked songs, you can always create a playlist, add all liked songs to it, export that, and then delete the temporary playlist.

**Comment by pitastrudl** [comment]
Thanks for the quick reply. I solved it by exporting the liked songs to a playlist. Short term solution.

**Comment by pavelkomarov** [comment]
You're welcome. I'll leave this issue open because it should maybe be addressed, but I'm unlikely to get to it in any reasonable amount of time.

**Comment by lamorton** [comment]
This issue has been solved in https://github.com/caseychu/spotify-backup. It shouldn't be to hard to port it here. I'll take a stab at a PR this weekend.

**Comment by pavel-aicradle** [comment]
Let me know if you need any help interpreting my javascript.

**Comment by dkipkaev** [comment]
Will this be fixed in this century?

**Comment by pavelkomarov** [comment]
I'm not actively updating this repo, but I'm happy to take and review a pull request.

**Comment by pavelkomarov** [comment]
As of a while ago, `liked songs` appears like another playlist to the user, but strangely Spotify's API still doesn't treat it that way.

It seems like this is probably the "[saved tracks](https://developer.spotify.com/documentation/web-api/reference/get-users-saved-tracks)" in the API. [stack overflow about it](https://stackoverflow.com/questions/70609721/how-to-access-my-liked-songs-in-spotify-python).

It can be added to the table as a row, but that row will have to be treated a little specially in the code, because export will make calls to a slightly different endpoint.

**Comment by pavelkomarov** [comment]
Added! https://github.com/pavelkomarov/exportify/commit/35a1aedb8e75a317091183b52e9dfb7329fbb159
